from utility.variables import projectName
from shoppingo.settings import FE_DOMAIN

def header(username):
    html_content = '<!DOCTYPE html><html><head>'
    html_content+= '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />'
    html_content+= '<meta name="viewport" content="width=device-width, initial-scale=1.0"/>'
    html_content+= '<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons|Material+Icons+Outlined" />'
    html_content+= '<style type="text/css">'
    html_content+= '#outlook a {padding:0;}'
    html_content+= 'body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}'
    html_content+= '.ExternalClass {width:100%;}'
    html_content+= '.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}'
    html_content+= '#backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}'
    html_content+= 'img {outline:none; text-decoration:none;border:none; -ms-interpolation-mode: bicubic;}'
    html_content+= 'a img {border:none;}'
    html_content+= '.image_fix {display:block;}'
    html_content+= 'p {margin: 0px 0px !important;}'
    html_content+= 'table td {border-collapse: collapse;}'
    html_content+= 'table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }'
    html_content+= 'span{color: #123A55;}'
    html_content+= 'a {color: #24B6F7;text-decoration: none;text-decoration:none!important;}'
    html_content+= '.button a { padding: .8em 1.5em; border: 1px solid #250c77; border-radius: .2rem;font-family: Roboto, Arial, sans-serif;'
    html_content+= 'font-size: 16px; color: #ffffff; text-decoration: none; font-weight: 400; display: inline-block;'
    html_content+= 'background-color:#250c77;}'
    html_content+= '.buttonLogMeIn {'
    html_content+= 'width: 350px; height: 45px; font-size: 13px; color: #fff; background-color: #250c77; border: 1px solid #250c77'
    html_content+= '!important; cursor: pointer; margin-left: 70px;}'
    html_content+= 'table[class=full] { width: 100%; clear: both; }'
    html_content+= '@media only screen and (max-width: 640px) {'
    html_content+= 'a[href^="tel"], a[href^="sms"] {'
    html_content+= 'text-decoration: none;'
    html_content+= 'color: #24B6F7;'
    html_content+= 'pointer-events: none;'
    html_content+= 'cursor: default;}'
    html_content+= '.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {'
    html_content+= 'text-decoration: default;'
    html_content+= 'color: #24B6F7 !important;'
    html_content+= 'pointer-events: auto;'
    html_content+= 'cursor: default;}'
    html_content+= 'table[class=devicewidth] {width: 460px!important;text-align:left!important;}'
    html_content+= 'td[class=devicewidth] {width: 440px!important;text-align:center!important;}'
    html_content+= 'img[class=devicewidth] {width: 440px!important;text-align:center!important;}'
    html_content+= 'img[class=banner] {width: 440px!important;height:147px!important;}'
    html_content+= 'table[class=devicewidthinner] {width: 440px!important;text-align:center!important;}'
    html_content+= 'table[class=icontext] {width: 345px!important;text-align:center!important;}'
    html_content+= 'img[class="colimg2"] {width:420px!important;height:243px!important;}'
    html_content+= 'table[class="emhide"]{display: none!important;}'
    html_content+= 'img[class="logo"]{}}'
    html_content+= '@media only screen and (max-width: 480px) {'
    html_content+= 'a[href^="tel"], a[href^="sms"] {'
    html_content+= 'text-decoration: none;'
    html_content+= 'color: #24B6F7;'
    html_content+= 'pointer-events: none;'
    html_content+= 'cursor: default;}'
    html_content+= '.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {'
    html_content+= 'text-decoration: default;'
    html_content+= 'color: #24B6F7 !important;'
    html_content+= 'pointer-events: auto;'
    html_content+= 'cursor: default;}'
    html_content+= 'table[class=devicewidth] {width: 300px!important;text-align:left!important;}'
    html_content+= 'td[class=devicewidth] {width: 140px!important;text-align:center!important; padding:10px !important;}'
    html_content+= 'img[class=devicewidth] {width: 280px!important;text-align:center!important;}'
    html_content+= 'table[class=devicewidthinner] {width: 280px!important;text-align:center!important;}'
    html_content+= 'table[class=icontext] {width: 186px!important;text-align:center!important;}'
    html_content+= 'table[class="emhide"]{display: none!important;}'
    html_content+= 'img[class="logo"]{}}'
    html_content+= '</style></head><body>'
    html_content+= '<table width="100%" bgcolor="#e8eaed" cellpadding="0" cellspacing="0" border="0" id="backgroundTable">'
    html_content+= '<tbody><tr><td>'
    html_content+= '<table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">'
    html_content+= '<tbody><tr><td width="100%">'
    html_content+= '<table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">'
    html_content+= '<tbody><tr><td><table width="100%" align="left" border="0" cellpadding="0" cellspacing="0" class="devicewidth">'
    html_content+= '<tbody><tr><td width="50%" align="left" valign="middle" style="background-color: #123A55; height:8px;">'
    html_content+= '</td><td width="50%" align="right" valign="middle" style="background-color: #EAB60F; height:8px;">'
    html_content+= '</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>'
    html_content+= '<table width="100%" bgcolor="#e8eaed" cellpadding="0" cellspacing="0" border="0" id="backgroundTable">'
    html_content+= '<tbody><tr><td><table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">'
    html_content+= '<tbody><tr><td width="100%"><table bgcolor="#ffffff" width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">'
    html_content+= '<tbody><tr><td width="100%" height="50"></td></tr><tr><td>'
    html_content+= '<img border="0" style="display:block; width:100px; padding-left:2.8em; padding-top:1em; border:none; '
    html_content+= f'outline:none; text-decoration:none;" src="https://i.postimg.cc/7Yq9Lq2L/unnamed-2.png" alt="{projectName} Logo" class="logo"></td></tr>'
    html_content+= '<tr><td width="100%" height="20"></td></tr>'
    html_content+= '<tr><td style="padding-left: 1em;"><table width="560" align="center" cellpadding="0" cellspacing="0" border="0" class="devicewidthinner">'
    html_content+= '<tbody><tr><td height="5"></td></tr>'
    html_content+= '<tr><td style="font-family: Roboto, arial, sans-serif; font-size: 13px; color: #333333;'
    html_content+= 'text-align:left;line-height: 24px;padding:1em; font-weight: 500">'
    
    html_content+= f'Hi {username},</td></tr>'
    
    html_content+= '<tr><td><p style="font-family: Roboto, arial, sans-serif; font-size: 13px; '
    return html_content

def footer(html_content):
    html_content+= '<tr><td><p style="font-family: Roboto, arial, sans-serif; font-size: 13px; color: #333333;'
    html_content+= 'text-align:left;line-height: 24px; padding:1em;">'
    
    html_content+= f'Kind Regards,<br><span>The {projectName} Team</span>'
    
   
    html_content+= '<img border="0" style="display:block; width:50px; padding-top:1em; border:none;'
    html_content+= f'outline:none; text-decoration:none;" src="https://i.postimg.cc/7Yq9Lq2L/unnamed-2.png" alt="{projectName} Logo"></p></td></tr>'
    html_content+= '<tr><td width="100%" height="20"></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>'
    html_content+= '<table width="100%" bgcolor="#e8eaed" cellpadding="0" cellspacing="0" border="0" id="backgroundTable">'
    html_content+= '<tbody><tr><td><table width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth"><tbody>'
    html_content+= '<tr><td width="100%"><table  bgcolor="#ffffff" width="600" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">'
    html_content+= '<tbody><tr><td width="100%" height="20"></td></tr><tr>'
    html_content+= '<td valign="middle" style="font-family: Roboto, arial, sans-serif; font-size: 12px;color: #454545;border-top:1px solid #ed642b;padding:2em;">'
    html_content+= '<p style="padding-bottom: 1em;">'
    html_content+= 'The information in this e-mail and in any attachment is confidential and may be priviledged. If you are not the intended recipient, then please destroy this message, '
    html_content+= f'delete any copies held on your systems and notify the <span>{projectName}</span> team immediately. Thank you.</p>'
    html_content+= f'<p style="padding-bottom: 1em;">To contact <span>{projectName}</span> or for further information on the'
    html_content+= f'services that {projectName} provide visit <a href="#/">{FE_DOMAIN}</a></p>'
    html_content+= '</td></tr><tr><td width="100%" height="20"></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></body></html>'
    
    return html_content


