# Generated by Django 4.2.4 on 2023-08-21 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_id", models.CharField(blank=True, max_length=50)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("razorpay_order_id", models.CharField(blank=True, max_length=50)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
