# Generated by Django 4.2.4 on 2023-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_payment_is_payment_status_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("authorised", "Authorised"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                max_length=20,
            ),
        ),
    ]
