# Generated by Django 4.2.4 on 2023-09-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
