# Generated by Django 4.2.4 on 2023-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, db_index=True),
        ),
    ]
