# Generated by Django 4.2.4 on 2023-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="brand_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="sub_category",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
