# Generated by Django 4.2.4 on 2023-09-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_lifecycle",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
    ]
